@Localhost = https://localhost:10000
@ConnectionName = RichillCapital.Binance

### Create brokerage order
POST {{Localhost}}/api/v1/brokerages/{{ConnectionName}}/orders
Content-Type: application/json

{
    "symbol": "BINANCE:BTCUSDT.P",
    "tradeType": "Buy",
    "orderType": "Market",
    "timeInForce": "IOC",
    "quantity": 1
}