@Localhost = https://localhost:10000
@ConnectionName = RichillCapital Brokerage Connection

### Stop brokerages
POST {{Localhost}}/api/v1/brokerages/stop
Content-Type: application/json

{
    "connectionName": "{{ConnectionName}}"
}