@Localhost = https://localhost:10000

### List Signals
GET {{Localhost}}/api/v1/signals?sortBy=id&order=desc

### Create signal
POST {{Localhost}}/api/v1/signals
Content-Type: application/json

{
    "sourceId": "Signal source id ",
    "time": "2024-06-26T18:00:08.000Z",
    "exchange": "Binance",
    "symbol": "BTCUSDT",
    "quantity": 1,
    "price": 1
}