@Localhost = https://localhost:10000

### Create Signal
POST {{Localhost}}/api/v1/signals
Content-Type: application/json

{
    "time": "2021-07-01T00:00:00Z",
    "side": "long",
    "behavior": "entry",
    "symbol": "BTCUSD",
    "quantity": 0.1,
    "price": 35000,
    "orderType": "Limit"
}
