@Localhost = https://localhost:10000

### Create Signal
POST {{Localhost}}/api/v1/signals
Content-Type: application/json

{
    "sourceId": "TV-Long-Task",
    "currentTime": "2024-06-15T18:02:24Z",
    "tradeType": "buy",
    "symbol": "BTCUSDT",
    "price": 100,
    "previousMarketPositionSize": 1,
    "previousMarketPosition": "short",
    "marketPositionSize": 0,
    "marketPosition": "flat"
}

### List signals 
GET {{Localhost}}/api/v1/signals