@Localhost = https://localhost:10000

### List Users
GET {{Localhost}}/api/v1/users


### Get User By Id
@UserId = UID0000001

GET {{Localhost}}/api/v1/users/{{UserId}}

### Create User
POST {{Localhost}}/api/v1/users
Content-Type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "password": "123test"
}