
@Localhost = https://localhost:10000
@Origin = RichillCapital.Quant.TradingView
@SourceId = TV-Long-Task

### Create signal
POST {{Localhost}}/api/v1/signals
Content-Type: application/json

{
    "time": "2025-09-01T00:00:00Z",
    "sourceId": "TV-Long-Task",
    "origin": "RichillCapital.Quant.TradingView",
    "symbol": "asd:asd",
    "tradeType": "buy",
    "orderType": "market",
    "quantity": 1
}