
@Localhost = https://localhost:10000
@Origin = RichillCapital.Quant.TradingView
@SourceId = TV-Long-Task

### Create signal
POST {{Localhost}}/api/v1/signals
Content-Type: application/json

{
    "time": "2021-07-01T00:00:00Z"
}