@Localhost = https://localhost:10000

### Create order
POST {{Localhost}}/api/v1/orders
Content-Type: application/json

{
    "accountId": "1",
    "symbol": "MSFT",
    "tradeType": "Buy",
    "orderType": "Market",
    "timeInForce": "IOC",
    "quantity": 100
}