@Localhost = https://localhost:10000

### Create signal source
POST {{Localhost}}/api/v1/signal-sources
Content-Type: application/json

{
    "id": "test",
    "name": "Test signal source",
    "description": "test signal source created from vscode rest client"
}