name: RichillCapital.Api CD

on:
  push:
    tags:
      - '*'
env:
    PROJECT_PATH: ./RichillCapital.Api.csproj
    IMAGE_NAME: api

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Version
      id: version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
    
    - name: Update Version
      run: |
        sudo apt-get install -y xmlstarlet
        assemblyVersion=${{ steps.version.outputs.version }}
        xmlstarlet ed --inplace -u "/Project/PropertyGroup/AssemblyVersion" -v "${assemblyVersion}" ${{ env.PROJECT_PATH }}    

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest . 
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Push Docker Image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest