name: ASP.NET Web API Continuous Deployment

on:
  push:
    tags:
      - '*'
env:
    Image_Name: api
    Tag: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: |
        docker build -t ${{ env.Image_Name }}:${{ env.Tag }} . 
        docker tag ${{ env.Image_Name }}:${{ env.Tag }} ${{ secrets.DOCKER_USERNAME }}/${{ env.Image_Name }}:${{ env.Tag }}

    - name: Push Docker Image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.Image_Name }}:${{ env.Tag }}