name: ASP.NET Web API Continuous Integration

on:
  push:
    branches: 
      - master

env:
  Build_Configuration: Debug
  Cake_File: build.cake
  Build_Target: Default
  Image_Name: api
  Tag: latest

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
          
    - name: .NET Build and Test
      uses: cake-build/cake-action@v2
      with:
        script-path: ${{ env.Cake_File }}
        target: ${{ env.Build_Target }}
        verbosity: Diagnostic
        arguments: |
          configuration: ${{ env.Build_Configuration }}
    
    - name: Build Docker Image
      run: |
        docker build -t ${{ env.Image_Name }}:${{ env.Tag }} . 

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RichillCapital.Api-${{ matrix.os }}-${{ env.Build_Configuration }}
        path: ./publish